import Head from 'next/head'
import AESCipher from '../helper/aes/aes'
import Cryptographie from '../component/cryptage/cryptographie'

export default function Home() {
  let algo = new AESCipher()
  return (
    <div className='container 'style={{borderRadius: '1rem',border: '6px solid black'}} >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      </Head>


           <Cryptographie algo={algo}/>


  </div>
  )
}
